// Generated by https://quicktype.io

export interface productModel {
    _id:        string;
    name:       string;
    restaurant: string;
    desc:       string;
    price:      number;
    genre:      string[];
    img:        string;
    rating:     number;
    __v:        number;
}
